fx_version 'cerulean'
games { 'gta5' }

this_is_a_map 'yes'

author'Grizmowe'

data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanctum_mlo'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanct_pil'
data_file 'DLC_ITYP_REQUEST' 'stream/g_sanc_uv_01'
data_file 'DLC_ITYP_REQUEST' 'stream/g_sanc_uv_02'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_gwen'
data_file 'DLC_ITYP_REQUEST' 'stream/ch_dlc_int_11_ch'
data_file 'DLC_ITYP_REQUEST' 'stream/ch_dlc_int_02_ch'
data_file 'DLC_ITYP_REQUEST' 'stream/bkr_biker_dlc_int_02'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanctum_mlo_shell_det_02'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_capea'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_capea_bois'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_cape_disp'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanctum_e'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_porte'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_shirt_tab'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_shirt_01'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_shelf_suu'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_stat'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_bar'
data_file 'DLC_ITYP_REQUEST' 'stream/hei_lev_des_mp_dlc'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_mural'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_shell_det_01'
data_file 'DLC_ITYP_REQUEST' 'stream/g_sanc_cafeuwu'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_tv'
data_file 'DLC_ITYP_REQUEST' 'stream/g_sanc_post2'
data_file 'DLC_ITYP_REQUEST' 'stream/g_sanc_post'
data_file 'DLC_ITYP_REQUEST' 'stream/g_prop_tv_stand_01'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_books'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_comic_shell'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_s_door'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_carp'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_drfata'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sanc_bar_02'
data_file 'DLC_ITYP_REQUEST' 'stream/g_prop_display_unit_01'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sol_da'
data_file 'DLC_ITYP_REQUEST' 'stream/griz_sol_da2'
